In [3]:
a=12324235423
b="vkfn"
print(f"{a:10} {b:10}")

12324235423 vkfn      


In [6]:
# list compression
list=["bbbb","daa"]
l=[x for x in list if 'bb' in x]
l

['bbbb']

In [11]:
add=lambda a:a+12
print(add(1))
print(type(add))

13
<class 'function'>


In [12]:
# pythonic way
add=lambda a,b:a*b
print(add(1,8))

9


In [13]:
add=lambda a,b,c:a*b*c
print(add(1,8,2))

16


In [14]:
%timeit mylist=[1,1,1]

38.4 ns ± 0.738 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [15]:
%timeit import numpy; myarray=numpy.array([1,2,3])

559 ns ± 1.45 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [1]:
%timeit mylist=list(range(1000000))

14.6 ms ± 254 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
%timeit import numpy; myarray=numpy.arange(1000000)

925 µs ± 61.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [12]:
%%timeit import numpy
myarray=numpy.arange(1000000)

986 µs ± 2.88 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [14]:
a=int(1.11)
a

1

In [33]:
import numpy
import time
size=10_00_000
list1=range(size)
list2=range(size)
array1=numpy.arange(size)
array2=numpy.arange(size)
initialTime=time.time()
resulttantList=[(a*b) for a,b in zip(list1,list2)]
print("Time taken by Lists :",
      (time.time()-initialTime),
      "seconds")
initialTime=time.time()
resulttantArray=array1*array2
print("Time taken by Numpy Array :",
      (time.time()-initialTime),
      "seconds")

Time taken by Lists : 0.08577680587768555 seconds
Time taken by Numpy Array : 0.0019278526306152344 seconds


In [30]:
import  numpy as np

In [25]:
import platform
print("Python version : "+platform.python_version())
print("Numpy version : "+np. __version__)
print("Numpy version : "+np. __version__)

Python version : 3.11.7
Numpy version : 1.26.4


In [27]:
a=100_00_00
a

1000000

In [34]:
a=1+2j
a

(1+2j)

In [44]:
arr=np.array([1,2,3],dtype='f4')
print(arr)
print(arr.dtype)

arr=np.array([1+2j,3-4j], dtype=np.complex64)
print(arr)
print(arr.dtype)

[1. 2. 3.]
float32
[1.+2.j 3.-4.j]
complex128


In [43]:
type(1+1j)

complex

In [50]:
arr=np.array([1+2j,3-4j])
print(arr)
print(arr.dtype)
print(type(arr))

[1.+2.j 3.-4.j]
complex128
<class 'numpy.ndarray'>


In [49]:
arr=[1+2j,2+3j]
print(arr)

[(1+2j), (2+3j)]


AttributeError: 'list' object has no attribute 'dtype'

In [62]:
arr=np.array(range(10))
print(arr)
print(type(arr))
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int32


In [61]:
arr=np.array([1,12,2,3,3,3,'banana'])
print(arr)
print(type(arr))
print(arr.dtype)

['1' '12' '2' '3' '3' '3' 'banana']
<class 'numpy.ndarray'>
<U11


In [72]:
arr=np.array([[1,2,3],[4,4,5]],dtype='i2')
print(arr[1,1])
print(arr.dtype)

4
int16


In [73]:
arr=np.arange(0,40,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]


In [76]:
zeros=np.zeros((3,3),dtype="i4")
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [77]:
empty=np.empty((3,3),dtype="i4")
empty

array([[4128860, 6029375, 3801155],
       [5570652, 6619251, 7536754],
       [ -65536,      -1,       0]])

In [83]:
arr=np.array([[1,2,3],[4,5,6]],dtype=np.int64)
arr
print(np.info(arr))

class:  ndarray
shape:  (2, 3)
strides:  (24, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x2580d78d190
byteorder:  little
byteswap:  False
type: int64
None


In [84]:
print(arr.shape)

(2, 3)


In [85]:
print(len(arr))

2


In [86]:
print(arr.size)

6


In [87]:
arr=np.array(range(100))

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [107]:
arr=np.array(range(100)).reshape((10,10))
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169

In [119]:
arr=np.array(range(100)).reshape((2,2,5,5))
print(arr)

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]
   [10 11 12 13 14]
   [15 16 17 18 19]
   [20 21 22 23 24]]

  [[25 26 27 28 29]
   [30 31 32 33 34]
   [35 36 37 38 39]
   [40 41 42 43 44]
   [45 46 47 48 49]]]


 [[[50 51 52 53 54]
   [55 56 57 58 59]
   [60 61 62 63 64]
   [65 66 67 68 69]
   [70 71 72 73 74]]

  [[75 76 77 78 79]
   [80 81 82 83 84]
   [85 86 87 88 89]
   [90 91 92 93 94]
   [95 96 97 98 99]]]]


In [122]:
print(arr[0][0])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [131]:
arr=np.array(range(100)).reshape((5,5,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]],

       [[20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]],

       [[80, 81, 82, 83],
        [84, 85, 86, 87],
        [88, 89, 90, 91],
        [92, 93, 94, 95],
        [96, 97, 98, 99]]])

In [130]:
print(arr[0:5,4:6])

[[[16 17 18 19]]

 [[36 37 38 39]]

 [[56 57 58 59]]

 [[76 77 78 79]]

 [[96 97 98 99]]]


In [136]:
arr=np.array(range(16)).reshape((2,2,2,2))
arr
print(arr[1, ...])

[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
